-- Create events table
create table events (
  id bigint generated by default as identity primary key,
  profile_id uuid references profiles(id) on delete cascade,
  device_id text references devices(id) on delete cascade,
  event text not null,
  domain text,
  url text,
  reason text,
  unlock_delay_ms integer,
  at timestamptz default timezone('utc', now())
);

create index on events (profile_id);
create index on events (device_id);

alter table events enable row level security;

create policy "Individuals can manage own events"
  on events
  for all
  using (auth.uid() = profile_id)
  with check (auth.uid() = profile_id);
