-- Create events table
create table events (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade,
  device_id uuid references devices(id) on delete cascade,
  event_type text not null,
  created_at timestamptz default timezone('utc', now())
);

create index on events (user_id);
create index on events (device_id);

alter table events enable row level security;

create policy "Individuals can manage own events"
  on events
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
